<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="TestEndpoint-20200704192430" tests="1" file=".py" time="0.006" timestamp="2020-07-04T19:24:30" failures="0" errors="0" skipped="0">
	<testcase classname="TestEndpoint" name="test_closeEndpoint" time="0.006" timestamp="2020-07-04T19:24:30" file="test_endpoint.py" line="16">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
Traceback (most recent call last):
  File "/root/tagdns/tagdns/endpoint.py", line 66, in run
  File "/root/tagdns/tagdns/endpoint.py", line 42, in closeAllEndpoint
    self.outbound.closeEndpoint()
  File "/root/tagdns/tagdns/endpoint.py", line 106, in closeEndpoint
    raise e
  File "/root/tagdns/tagdns/endpoint.py", line 101, in closeEndpoint
    self.__queue.put()
AttributeError: 'Outbound' object has no attribute '_Outbound__queue'
]]></system-err>
	</testcase>
</testsuite>
